version: "3.8"
services:
  # =================================================
  # POSTGRES SERVER
  # =================================================
  pg-docker:
    user: root
    image: postgres:14-alpine
    container_name: ccca_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - pg_storage:/var/lib/postgresql/data
    networks:
      - dev-network

# =================================================
# NETWORK
# =================================================
networks:
  dev-network:
    driver: bridge

# =================================================
# VOLUMES
# =================================================
volumes:
  pg_storage: